
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftmasmenosleftpordiventero pa_cerrado pa_abierto menos mas por divinit : EE  : E mas E\n           | E menos E \n           | E por E\n           | E div E\n           | pa_abierto E pa_cerrado  \n           E : entero'
    
_lr_action_items = {'pa_abierto':([0,3,5,6,7,8,],[3,3,3,3,3,3,]),'entero':([0,3,5,6,7,8,],[4,4,4,4,4,4,]),'$end':([1,2,4,10,11,12,13,14,],[0,-1,-7,-2,-3,-4,-5,-6,]),'mas':([2,4,9,10,11,12,13,14,],[5,-7,5,-2,-3,-4,-5,-6,]),'menos':([2,4,9,10,11,12,13,14,],[6,-7,6,-2,-3,-4,-5,-6,]),'por':([2,4,9,10,11,12,13,14,],[7,-7,7,7,7,-4,-5,-6,]),'div':([2,4,9,10,11,12,13,14,],[8,-7,8,8,8,-4,-5,-6,]),'pa_cerrado':([4,9,10,11,12,13,14,],[-7,14,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'E':([0,3,5,6,7,8,],[2,9,10,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> E','init',1,'p_S_','gramatica.py',56),
  ('E -> E mas E','E',3,'p_operaciones','gramatica.py',66),
  ('E -> E menos E','E',3,'p_operaciones','gramatica.py',67),
  ('E -> E por E','E',3,'p_operaciones','gramatica.py',68),
  ('E -> E div E','E',3,'p_operaciones','gramatica.py',69),
  ('E -> pa_abierto E pa_cerrado','E',3,'p_operaciones','gramatica.py',70),
  ('E -> entero','E',1,'p_Entero','gramatica.py',88),
]
